### PR TITLE
Fix watching of entry points

### LINKED ISSUE #2139: CLI: watch doesnt work after upgrading to 4.6.0
After upgrading from 4.5.3 the command below has stopped working. Changing the scss file does nothing:

`"css": "./node_modules/.bin/node-sass -w scss/style.scss public/css/style.css"`

- NPM version: 5.5.1
- Node version: 8.9.0
- Node Process:
  - http_parser: 2.7.0
  - node: 8.9.0
  - v8: 6.1.534.46
  - uv: 1.15.0
  - zlib: 1.2.11
  - ares: 1.10.1-DEV
  - modules: 57
  - nghttp2: 1.25.0
  - openssl: 1.0.2l
  - icu: 59.1
  - unicode: 9.0
  - cldr: 31.0.1
  - tz: 2017b
- Node Platform: linux
- Node architecture: x64
- npm node-sass versions: 4.6.0

### PR DESCRIPTION
**Pull request by xzyfer**
Currently changes to non-partials are being picked up. This PR fixes
that and adds addition test coverage.

Fixes #2139

### CODE REVIEW

File: lib/watcher.js [hunk 1]
```diff
@@ -30,8 +31,14 @@ watcher.changed = function(absolutePath) {
 
   this.reset();
 
+  if (absolutePath && path.basename(absolutePath)[0] !== '_') {
```
Comment (xzyfer) [inline lib/watcher.js]: This was the crux of the change here. The rest is just simplification.

**Comment by xzyfer** [comment]
I believe the three remaining failures may be bugs in sass-graph. I'll continue to investigate.
