### PR TITLE
Handle permission errors when attempting to cache binaries

### LINKED ISSUE #1781: Recieve error when install node-sass by yarn .
I have installed node-sass by yarn, but I get error: 
```
error /home/zendkofy/public_html/react-redux/visualsliderdesigner/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/install.js
Directory: /home/zendkofy/public_html/react-redux/visualsliderdesigner/node_modules/node-sass
Output:
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at /home/zendkofy/public_html/react-redux/visualsliderdesigner/node_modules/node-sass/scripts/install.js:122:26
    at /home/zendkofy/public_html/react-redux/visualsliderdesigner/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
Could you please let me know to fix this error ?

### PR DESCRIPTION
**Pull request by xzyfer**
This uses a candidate model for determining an suitable cache
directory. This is different from the current approach with eagerly
chooses a cache directory. If that directory isn't accessible for
some reason (i.e. permissions) we have to bail out. With this
approach we can try a prioritised list of candidate directories.

Additionally this address the case where npm cache config is
blank.

Fixes #1781

### CODE REVIEW

**Comment by xzyfer** [comment]
This is super messy but gets the job done.

**Comment by mriehema** [comment]
Node-sass 3.11.0 included caching the binaries (#1554). Yarn caused a problem and you removed it in 3.11.1 and this is a new fixed PR with caching again for a future version. Did I get it right?

**Comment by xzyfer** [comment]
>Node-sass 3.11.0 included caching the binaries

Correct. 

> Yarn caused a problem and you removed it in 3.11.1 

Yes and no. We removed it due to two issues.

1) we were querying npm for it's cache directory, and using it. However npm scripts run under a restricted user which may not have write permissions to that directory.

2) yarn isn't correctly handling npm config the same as npm (see https://github.com/yarnpkg/yarn/issues/1632). The result of this issue is that we would receive `''` as the cache directory. We were not handling this gracefully.

> this is a new fixed PR with caching again for a future version

Correct. We are re-enabling the caching. This time have a set of candidate directories (this was in your original PR but was removed) which could be used a cache. We try each one until we find out that is writeable and use it. Otherwise we fallback to the `vendor` directory which is the same as not caching.

**Comment by xzyfer** [comment]
@nschonni this is pretty close now, care to take a look?

**Comment by mriehema** [comment]
@xzyfer Thank you!

File: lib/extensions.js [hunk 1]
```diff
@@ -260,6 +261,80 @@ function getBinaryPath() {
...
 
 /**
+ * An array of paths suitable for use as a local disk cache of the binding.
+ *
+ * @return {[]String} an array of paths
+ * @api public
+ */
+function getCachePathCandidates() {
+  return [
+    process.env.npm_config_sass_binary_cache,
```
Comment (nschonni) [inline lib/extensions.js]: Maybe, just use `||` for falsey checking instead of the filter

Comment (nschonni) [inline lib/extensions.js]: Nevermind, saw that you're looping through later, so you want all truethy values

File: lib/extensions.js [hunk 2]
```diff
@@ -260,6 +261,80 @@ function getBinaryPath() {
...
+ *
+ * @return {String} directory to cache binding
+ * @api public
+ */
+function getBinaryCachePath() {
+  var i,
+    cachePath,
+    cachePathCandidates = getCachePathCandidates();
+
+  for (i = 0; i < cachePathCandidates.length; i++) {
```
Comment (nschonni) [inline lib/extensions.js]: Since the `i` isn't used outside of the element lookup, `foreach in` might be better

File: lib/extensions.js [hunk 3]
```diff
@@ -260,6 +261,80 @@ function getBinaryPath() {
...
+ * @api public
+ */
+function getCachedBinary() {
+  var i,
+    cachePath,
+    cacheBinary,
+    cachePathCandidates = getCachePathCandidates(),
+    binaryName = getBinaryName();
+
+  for (i = 0; i < cachePathCandidates.length; i++) {
```
Comment (nschonni) [inline lib/extensions.js]: `foreach`

File: scripts/install.js [hunk 4]
```diff
@@ -92,37 +92,47 @@ function download(url, dest, cb) {
  */
 
 function checkAndDownloadBinary() {
-  if (sass.hasBinary(sass.getBinaryPath())) {
+  if (process.env.SKIP_SASS_BINARY_DOWNLOAD_FOR_CI) {
+    console.log('Skipping downloading binaries on CI builds');
```
Comment (nschonni) [inline scripts/install.js]: Might want to use the npmlog stuff from the other PR

File: lib/extensions.js [hunk 5]
```diff
@@ -260,6 +261,80 @@ function getBinaryPath() {
...
+ * An array of paths suitable for use as a local disk cache of the binding.
+ *
+ * @return {[]String} an array of paths
+ * @api public
+ */
+function getCachePathCandidates() {
+  return [
+    process.env.npm_config_sass_binary_cache,
+    process.env.npm_config_cache,
+    getBinaryPath(),
```
Comment (nschonni) [inline lib/extensions.js]: I think this should be removed since it's not really a cache path, but the final fallback

File: scripts/install.js [hunk 6]
```diff
@@ -92,37 +92,47 @@ function download(url, dest, cb) {
...
     return;
   }
+  var binaryPath = sass.getBinaryPath();
 
-  mkdir(path.dirname(sass.getBinaryPath()), function(err) {
+  if (sass.hasBinary(binaryPath)) {
+    return;
+  }
+
+  mkdir(path.dirname(binaryPath), function(err) {
```
Comment (nschonni) [inline scripts/install.js]: Since it looks like fs.stat https://nodejs.org/api/fs.html#fs_fs_stat_path_callback isn't supposed to be called before doing the write, maybe try to create the cachePath here, then fallback to the vendor if it can't

File: lib/extensions.js (hunk 2 above)
Comment (xzyfer) [inline lib/extensions.js]: `forEach` makes exiting early very messy.

File: lib/extensions.js (hunk 3 above)
Comment (xzyfer) [inline lib/extensions.js]: `forEach` makes exiting early very messy.

File: scripts/install.js (hunk 4 above)
Comment (xzyfer) [inline scripts/install.js]: This was already here, it has just been moved. The npmlog issue is a separate concern.

File: scripts/install.js (hunk 6 above)
Comment (xzyfer) [inline scripts/install.js]: I'm not sure what `fs.stat` has to do with `mkdirp`? 

Having the vendor directory in the cache candidates list means that if we can't write to the npm cache path then we are writing to vendor. The fallback has already happened.

File: scripts/install.js [hunk 7]
```diff
@@ -92,37 +92,47 @@ function download(url, dest, cb) {
...
+
+    download(sass.getBinaryUrl(), cacheBinary, function(err) {
       if (err) {
         console.error(err);
         return;
       }
 
-      console.log('Binary downloaded and installed at', sass.getBinaryPath());
+      console.log('Binary downloaded to ' + cacheBinary);
+      fs.createReadStream(cacheBinary).pipe(fs.createWriteStream(binaryPath));
```
Comment (xzyfer) [inline scripts/install.js]: The worse case here is that we risk copying from the vendor dir to the vendor dir. Could be problematic.

File: lib/extensions.js (hunk 2 above)
Comment (xzyfer) [inline lib/extensions.js]: Expanding on this, `forEach` is intended to creating side effects. This is closer to a `reduce` but that also really messy to exit early from.

File: scripts/install.js (hunk 6 above)
Comment (xzyfer) [inline scripts/install.js]: Are you suggesting we move the `mkdir` into the `download` callback?

File: lib/extensions.js (hunk 5 above)
Comment (xzyfer) [inline lib/extensions.js]: I'm not sure, I need to think about this. In the install script we only ever care about the final destination. The edge case is that it's possible for the cache directory and vendor directory to be one and the same.

Comment (xzyfer) [inline lib/extensions.js]: Nope, you're completely right, this is a bad abstraction.

**Comment by xzyfer** [comment]
I made some revisions. I'm not in love with it but it's an improvement. IMHO the install script needs a lot of love.
